repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.1 # Use the latest version of the ruff pre-commit hook
  hooks:
  - id: ruff
    args: [ --fix ]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.1 # Use the latest version of mypy
  hooks:
  - id: mypy

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.6.0 # Use the latest version of conventional-pre-commit
  hooks:
  - id: conventional-pre-commit
    stages: [ commit-msg ]
    args: []
